version: "3"

services:
    publisher:
        build: 
            context: .
            dockerfile: ./publisher.Dockerfile
        environment:
            - AWS_ACCESS_KEY_ID
            - AWS_SECRET_ACCESS_KEY
            - AWS_DEFAULT_REGION
            - PYTHONIONENCODING=UTF-8
            - PYTHONUNBUFFERED=1

    product-worker:
        build: 
            context: .
            dockerfile: ./product-worker.Dockerfile
        environment:
            - AWS_ACCESS_KEY_ID
            - AWS_SECRET_ACCESS_KEY
            - AWS_DEFAULT_REGION
            - PYTHONIONENCODING=UTF-8
            - PYTHONUNBUFFERED=1
    
    review-worker:
        build: 
            context: .
            dockerfile: ./review-worker.Dockerfile
        environment:
            - AWS_ACCESS_KEY_ID
            - AWS_SECRET_ACCESS_KEY
            - AWS_DEFAULT_REGION
            - PYTHONIONENCODING=UTF-8
            - PYTHONUNBUFFERED=1
    
