service: crawler

plugins:
  - serverless-python-requirements

provider:
  name: aws
  region: us-east-2
  runtime: python3.8

functions:
  hello:
    handler: deploy/handler.run
    
custom:
  pythonRequirements:
    dockerizePip: 'non-linux'
